### ISSUE TITLE
Error with create-test

### ISSUE THREAD

**Issue by MelSFNL** [silverfin/sf-toolkit#43]
Error message from CLI:

melle.meertens@Melle-Meertenss-MacBookAir be_market % silverfin create-test -u https://live.getsilverfin.com/f/14400/1290026/ledgers/27963625/workflows/2280506/reconciliation_texts/56583086#
Response Status: 200 (OK) - method: get - url: /companies/1290026/periods/27963625/reconciliations/56583086#
Response Status: 200 (OK) - method: get - url: /companies/1290026/periods
Response Status: 200 (OK) - method: get - url: /companies/1290026/periods/27963625/reconciliations/56583086#/custom

!!! Please open an issue including this log on https://github.com/silverfin/sf-toolkit/issues

customArray is not iterable
silverfin: v1.9.2, node: v20.2.0

TypeError: customArray is not iterable
    at Object.processCustom (/opt/homebrew/lib/node_modules/sf_toolkit/lib/utils/liquidTestUtils.js:99:16)
    at Object.testGenerator (/opt/homebrew/lib/node_modules/sf_toolkit/lib/liquidTestGenerator.js:87:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by MelSFNL** [comment]
Due to the # in the URL
